### ISSUE TITLE
Unbounded scene? 

### ISSUE THREAD

**Issue by antithing** [wolfball/PlenVDB#2]
Hi, thanks for making this project available!
 I have the examples loading into a game engine.

Will this work on unbounded scenes as well as objects?
Is there a way to include color information as well as the geometry?

Thanks!

**Comment by wolfball** [comment]
Hi, thanks for your interest!

#### 1. Unbounded scenes: 
Yes, our work only focuses on a novel data structure (VDB), so theoretically it can be adapted to other approaches. Since our baseline (DVGO) supports unbounded scenarios, we are able to support it as well.

Take *Garden* in [Mip-NeRF-360](https://jonbarron.info/mipnerf360/) for example:
```bash
python run.py --config configs/nerf_unbounded/garden.py
python run.py --config configs/nerf_unbounded/garden.py --render_only --render_video
```

However, we have not implemented efficient renderer for MergedVDB with unbounded scenes, so *vdb_compression.py* is not used.

#### 2. **Color information**:
Unfortunately, it's not possible to visualize colors directly in Blender right now, at least I don't know how to do that.

For one thing, our ColorVDB holds high-dimensional color feature vectors instead of the commonly used RGB; For another, I don't know the production process of VDBs in VFX very well, and I'm not sure what they do with color. 

But I think it's achievable and a worthwhile direction to learn and explore.

**Comment by antithing** [comment]
Thank you!  I will test some unbounded scenes. Color is very important for our (VFX) use case, generally we would store the (float) data as RGBA, with Red, Green, Blue and Density values mapped to the variables. Is this possible to do using this code?

Thank you again!

**Comment by wolfball** [comment]
This code is not working yet.

**Comment by antithing** [comment]
Okay thank you. Please let me know if you want me to test any updates!
